[project]
name = "ee2802"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiohttp",
    "imagesize>=1.4.1",
    "matplotlib",
    "opencv-python>=4.11.0.86",
    "pandas",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.2",
    "seaborn",
    "torch",
    "torchmetrics>=1.0.3",
    "torchvision",
    "tqdm",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu130"

[dependency-groups]
dev = [
    "pandas-stubs",
]
